# place the status bar on top
set-option -g status-position top

# hide status bar by default
set-option -g status off

set-option -g status-style "bg=colour235,default"  

set-window-option -g window-status-current-style "bg=colour33,fg=colour255,bold"

set-window-option -g window-status-style "bg=colour235,fg=colour244"

# Start windows numbering at 1
set-option -g base-index 1

# hide right contents
set-option -g status-right ""

# use <bind-key> + b to toogle status bar
bind-key b set-option status
