# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" bash -c "tmux attach || tmux new -s Work"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT ALT, M, Music TUI, exec, omarchy-launch-or-focus-tui cliamp
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER SHIFT ALT, A, Grok, exec, omarchy-launch-webapp "https://grok.com"
bindd = SUPER SHIFT, Y, YouTube, exec, omarchy-launch-webapp "https://youtube.com/"
bindd = SUPER SHIFT ALT, G, WhatsApp, exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, X, X, exec, omarchy-launch-webapp "https://x.com/"
bindd = SUPER SHIFT ALT, X, X Post, exec, omarchy-launch-webapp "https://x.com/compose/post"

# Add extra bindings
# bind = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Replace Omarchy's default Mako notification bindings with SwayNC.
unbind = SUPER, COMMA
unbind = SUPER SHIFT, COMMA
unbind = SUPER CTRL, COMMA
unbind = SUPER ALT, COMMA
unbind = SUPER SHIFT ALT, COMMA
bindd = SUPER, COMMA, Dismiss latest notification, exec, swaync-client --close-latest --skip-wait
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, swaync-client --close-all --skip-wait
bindd = SUPER CTRL, COMMA, Toggle notification DND, exec, sh -c 'swaync-client --toggle-dnd --skip-wait && pkill -RTMIN+10 waybar'
bindd = SUPER ALT, COMMA, Open notification center, exec, swaync-client --toggle-panel --skip-wait
bindd = SUPER SHIFT ALT, COMMA, Restore notification center, exec, swaync-client --open-panel --skip-wait

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# Logitech MX Keys
# bind = SUPER SHIFT, S, exec, omarchy-capture-screenshot      # Print Screen Button
# bind = SUPER, H, exec, voxtype record toggle                 # Dictation Button
# bind = SUPER, PERIOD, exec, omarchy-launch-walker -m symbols # Emoji Button
