# Change the default Omarchy look'n'feel

# https://wiki.hypr.land/Configuring/Basics/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 5
    gaps_out = 5
    border_size = 2

    # Change to niri-like side-scrolling layout
     layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    dim_inactive = true
    dim_strength = 0.1
   
  blur {
        enabled = true
        size = 12
        passes = 3
        new_optimizations = true
        noise = 0.1
        special = true
        popups = true
        input_methods = true
  }
  active_opacity = 0.95
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    enabled = true

    bezier = smooth,   0.05, 0.9, 0.1, 1.0
    bezier = overshot, 0.05, 0.9, 0.1, 1.05

    animation = windows,    1, 6, overshot, slide
    animation = windowsOut, 1, 5, smooth,   popin 80%
    animation = fade,       1, 6, smooth
    animation = workspaces, 1, 5, overshot, slide
}


# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}
